include:
  - openstack.env
  - chronyd.install
  - httpd.install
  - mariadb.env
  - rabbitmq.env
  - openstack.keystone.install
  - openstack.glance.install
  - openstack.nova.controller
  - openstack.neutron.install
  - openstack.dashboard.install
  - openstack.cinder.install
